---
# This is a basic workflow to help you get started with Actions

name: PR - Open

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

# A workflow run is made up of one or more jobs,
# that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE,
  #     # so your job can access it
  #     - uses: actions/checkout@v4
  #     # Runs a single command using the runners shell
  #     - name: Run Super-Linter
  #       uses: github/super-linter@v4
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}
      git-proposed-tag: ${{ steps.git-proposed-tag.outputs.git-proposed-tag }}
      git-current-branch: ${{ steps.git-current-branch.outputs.git-current-branch }}
      git-old-branch: ${{ steps.git-old-branch.outputs.git-old-branch }}
      docker-tags: ${{ steps.docker-tag.outputs.docker-tag }}
  build:
    runs-on: ubuntu-latest
    needs:
      setup
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - name: "Docker Tags"
        shell: bash
        run: echo "${{ needs.setup.outputs.docker-tags }}"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ needs.setup.outputs.docker-tags }}
          push: true
          # Set version to proposed tag if master, otherwise set version as branch name
          build-args: version=${{ needs.setup.outputs.git-proposed-tag }}

